tester(github): make "not in PATH" test more informative
This change make the test emit a message for successful test and failure
instead of relying on `which` default error message for "not found",
which might confuse others.

Also the change get rid of the syntax that trips the YAML parser.

diff --git a/.github/workflows/tester.yml b/.github/workflows/tester.yml
--- a/.github/workflows/tester.yml
+++ b/.github/workflows/tester.yml
@@ -38,7 +38,13 @@ jobs:
       - if: '! matrix.addPath'
         name: Verify installation not in PATH
         shell: bash
-        run: ! which nim
+        run: |
+          if ! which nim >/dev/null 2>&1; then
+            echo "Test passed!"
+          else
+            echo "Test failed!"
+            exit 1
+          fi
 
       - name: Verify installation in correct folder
         shell: bash
