tester(github): use a more verbose test for nimble PATH check

diff --git a/.github/workflows/tester.yml b/.github/workflows/tester.yml
--- a/.github/workflows/tester.yml
+++ b/.github/workflows/tester.yml
@@ -76,4 +76,6 @@ jobs:
         shell: bash
         run: |
           nimble install -y karax nimterop
-          toast -h >/dev/null 2>&1
+          if ! command -v toast >/dev/null 2>&1; then
+            echo "Error: could not found toast"
+          fi
